name: subcribe
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.4.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  shared_preferences: ^2.3.2
  easy_localization: ^3.0.7
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1
  fluttertoast: ^8.2.8
  flutter_bloc: ^8.1.6
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.4
  file_picker: ^8.1.3
  image_picker: ^1.1.2
  flutter_tts: ^4.2.0
#  receive_sharing_intent: ^1.8.1
  google_sign_in: ^6.2.2
  flutter_launcher_icons: ^0.13.1

  camera: ^0.11.0+2
  url_launcher: ^6.3.1
  intl: ^0.19.0
  in_app_purchase: ^3.2.0
#  cloud_firestore: ^5.6.0


dev_dependencies:

  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  background_color: "#FFFFFF"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/translations/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700